/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    BudgetOptimizer: typeof import('./components/BudgetOptimizer.vue')['default']
    BudgetOverview: typeof import('./components/BudgetOverview.vue')['default']
    Calendar: typeof import('./components/Calendar.vue')['default']
    ExpensesListe: typeof import('./components/ExpensesListe.vue')['default']
    FinanceSummary: typeof import('./components/FinanceSummary.vue')['default']
    ModalExpenses: typeof import('./components/ModalExpenses.vue')['default']
    Param: typeof import('./components/param.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLogo: typeof import('./components/SelectLogo.vue')['default']
    VisualRepresentation: typeof import('./components/VisualRepresentation.vue')['default']
  }
}
